import '../models/project.dart';
import '../models/room.dart';
import '../models/electrical_point.dart';
import '../models/circuit.dart';
import '../models/boq_item.dart';

class MockData {
  MockData._();

  static List<Project> getProjects() {
    return [
      Project(
        id: 'proj-001',
        name: 'Modern Family House',
        client: 'Dr. Emmanuel R.',
        buildingType: 'Residential',
        location: 'Kigali, Kicukiro',
        standard: 'RS IEC 60364',
        notes: 'Four-bedroom modern family villa with open plan kitchen and solar PV provision.',
        status: ProjectStatus.active,
        currentStage: ProjectStage.electricalDesign,
        updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        floorPlanName: 'Kicukiro_Villa_Architectural_Plan.png',
        roomsCount: 8,
        electricalPointsCount: 24,
        circuitsCount: 5,
        estimatedCostRwf: 1245000,
      ),
      Project(
        id: 'proj-002',
        name: '3 Bedroom Residence',
        client: 'Claire Uwase',
        buildingType: 'Residential',
        location: 'Kigali, Gacuriro',
        standard: 'RS IEC 60364',
        notes: 'Single storey residential dwelling with backup inverter wiring.',
        status: ProjectStatus.completed,
        currentStage: ProjectStage.report,
        updatedAt: DateTime.now().subtract(const Duration(days: 1)),
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        floorPlanName: 'Gacuriro_Residence_Plan_Final.pdf',
        roomsCount: 7,
        electricalPointsCount: 22,
        circuitsCount: 4,
        estimatedCostRwf: 980000,
      ),
      Project(
        id: 'proj-003',
        name: 'Office Renovation',
        client: 'Inzovu Capital Ltd',
        buildingType: 'Office',
        location: 'Kigali CBD, Nyarugenge',
        standard: 'BS 7671',
        notes: 'Commercial fit-out floor 3. Dedicated clean power for server room.',
        status: ProjectStatus.reviewRequired,
        currentStage: ProjectStage.boq,
        updatedAt: DateTime.now().subtract(const Duration(days: 3)),
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
        floorPlanName: 'Inzovu_Office_L3_Cad.png',
        roomsCount: 12,
        electricalPointsCount: 54,
        circuitsCount: 9,
        estimatedCostRwf: 3450000,
      ),
      Project(
        id: 'proj-004',
        name: 'Heights Apartment 4B',
        client: 'Kigali Real Estate',
        buildingType: 'Apartment',
        location: 'Kigali, Kimihurura',
        standard: 'RS IEC 60364',
        notes: 'Apartment unit pre-installation for automated load control.',
        status: ProjectStatus.inProgress,
        currentStage: ProjectStage.aiAnalysis,
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        floorPlanName: 'Heights_4B_Architectural.jpg',
        roomsCount: 5,
        electricalPointsCount: 18,
        circuitsCount: 4,
        estimatedCostRwf: 760000,
      ),
    ];
  }

  static List<Room> getRooms() {
    return const [
      Room(
        id: 'room-lr',
        name: 'Living Room',
        areaM2: 28.5,
        pointsCount: 7,
        description: 'Main lounge & entertainment area',
      ),
      Room(
        id: 'room-kit',
        name: 'Kitchen',
        areaM2: 14.2,
        pointsCount: 8,
        description: 'Cooking, preparation, and refrigeration area',
      ),
      Room(
        id: 'room-mb',
        name: 'Master Bedroom',
        areaM2: 18.0,
        pointsCount: 5,
        description: 'En-suite master bedroom with walk-in closet',
      ),
      Room(
        id: 'room-b1',
        name: 'Bedroom 1',
        areaM2: 13.5,
        pointsCount: 4,
        description: 'Standard guest/child bedroom',
      ),
      Room(
        id: 'room-b2',
        name: 'Bedroom 2',
        areaM2: 12.0,
        pointsCount: 4,
        description: 'Standard guest/child bedroom',
      ),
      Room(
        id: 'room-bth',
        name: 'Bathroom',
        areaM2: 4.8,
        pointsCount: 2,
        description: 'Wet area with IP44 rated fixtures',
      ),
      Room(
        id: 'room-cor',
        name: 'Corridor & Foyer',
        areaM2: 8.5,
        pointsCount: 3,
        description: 'Circulation space housing Main Distribution Board',
      ),
      Room(
        id: 'room-ver',
        name: 'Veranda & Patio',
        areaM2: 11.0,
        pointsCount: 3,
        description: 'Semi-outdoor covered porch',
      ),
    ];
  }

  static List<ElectricalPoint> getElectricalPoints() {
    return const [
      // Living Room
      ElectricalPoint(
        id: 'pt-001',
        roomId: 'room-lr',
        roomName: 'Living Room',
        type: ElectricalPointType.light,
        label: 'Ceiling Center Chandelier/Light',
        quantity: 1,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-01',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.28,
        yRatio: 0.32,
      ),
      ElectricalPoint(
        id: 'pt-002',
        roomId: 'room-lr',
        roomName: 'Living Room',
        type: ElectricalPointType.downlight,
        label: 'Perimeter Accent Downlights (Pair)',
        quantity: 2,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-01',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.20,
        yRatio: 0.22,
      ),
      ElectricalPoint(
        id: 'pt-003',
        roomId: 'room-lr',
        roomName: 'Living Room',
        type: ElectricalPointType.socketDouble,
        label: 'TV Media Console Double Socket',
        quantity: 2,
        cableSize: '2.5 mm²',
        circuitId: 'SOCKET-01',
        protectionMcb: '20A MCB',
        status: 'Recommended',
        xRatio: 0.12,
        yRatio: 0.35,
      ),
      ElectricalPoint(
        id: 'pt-004',
        roomId: 'room-lr',
        roomName: 'Living Room',
        type: ElectricalPointType.tvPoint,
        label: 'Coaxial & Data TV Point',
        quantity: 1,
        cableSize: 'Cat6 UTP',
        circuitId: 'DATA-01',
        protectionMcb: 'Surge Protected',
        status: 'Recommended',
        xRatio: 0.12,
        yRatio: 0.42,
      ),
      ElectricalPoint(
        id: 'pt-005',
        roomId: 'room-lr',
        roomName: 'Living Room',
        type: ElectricalPointType.socketDouble,
        label: 'Sofa Side Convenience Socket',
        quantity: 2,
        cableSize: '2.5 mm²',
        circuitId: 'SOCKET-01',
        protectionMcb: '20A MCB',
        status: 'Preliminary',
        xRatio: 0.38,
        yRatio: 0.45,
      ),
      ElectricalPoint(
        id: 'pt-006',
        roomId: 'room-lr',
        roomName: 'Living Room',
        type: ElectricalPointType.switchPoint,
        label: '2-Gang 2-Way Wall Switch',
        quantity: 1,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-01',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.42,
        yRatio: 0.25,
      ),

      // Kitchen
      ElectricalPoint(
        id: 'pt-007',
        roomId: 'room-kit',
        roomName: 'Kitchen',
        type: ElectricalPointType.light,
        label: 'Kitchen Ceiling Fluorescent/LED Batten',
        quantity: 2,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-01',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.72,
        yRatio: 0.28,
      ),
      ElectricalPoint(
        id: 'pt-008',
        roomId: 'room-kit',
        roomName: 'Kitchen',
        type: ElectricalPointType.cookerPoint,
        label: 'Induction Cooker / Oven Point',
        quantity: 1,
        cableSize: '4.0 mm²',
        circuitId: 'KITCHEN-01',
        protectionMcb: '25A MCB',
        status: 'Review Required',
        xRatio: 0.88,
        yRatio: 0.18,
      ),
      ElectricalPoint(
        id: 'pt-009',
        roomId: 'room-kit',
        roomName: 'Kitchen',
        type: ElectricalPointType.socketDouble,
        label: 'Kitchen Countertop Sockets (Dual)',
        quantity: 4,
        cableSize: '2.5 mm²',
        circuitId: 'SOCKET-02',
        protectionMcb: '20A MCB',
        status: 'Recommended',
        xRatio: 0.82,
        yRatio: 0.38,
      ),
      ElectricalPoint(
        id: 'pt-010',
        roomId: 'room-kit',
        roomName: 'Kitchen',
        type: ElectricalPointType.socketSingle,
        label: 'Dedicated Refrigerator Socket',
        quantity: 1,
        cableSize: '2.5 mm²',
        circuitId: 'SOCKET-02',
        protectionMcb: '20A MCB',
        status: 'Recommended',
        xRatio: 0.65,
        yRatio: 0.18,
      ),

      // Corridor & Distribution Board
      ElectricalPoint(
        id: 'pt-011',
        roomId: 'room-cor',
        roomName: 'Corridor & Foyer',
        type: ElectricalPointType.distributionBoard,
        label: 'Main 8-Way Distribution Board (DB-1)',
        quantity: 1,
        cableSize: '16.0 mm² Sub-main',
        circuitId: 'MAIN-DB',
        protectionMcb: '63A 30mA RCD Main',
        status: 'Recommended',
        xRatio: 0.50,
        yRatio: 0.48,
      ),
      ElectricalPoint(
        id: 'pt-012',
        roomId: 'room-cor',
        roomName: 'Corridor & Foyer',
        type: ElectricalPointType.light,
        label: 'Hallway Recessed Downlight',
        quantity: 2,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-01',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.50,
        yRatio: 0.35,
      ),

      // Master Bedroom
      ElectricalPoint(
        id: 'pt-013',
        roomId: 'room-mb',
        roomName: 'Master Bedroom',
        type: ElectricalPointType.light,
        label: 'Ceiling Pendant Light',
        quantity: 1,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-02',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.25,
        yRatio: 0.72,
      ),
      ElectricalPoint(
        id: 'pt-014',
        roomId: 'room-mb',
        roomName: 'Master Bedroom',
        type: ElectricalPointType.socketDouble,
        label: 'Bedside Double Sockets (Left/Right)',
        quantity: 2,
        cableSize: '2.5 mm²',
        circuitId: 'SOCKET-03',
        protectionMcb: '20A MCB',
        status: 'Recommended',
        xRatio: 0.15,
        yRatio: 0.78,
      ),
      ElectricalPoint(
        id: 'pt-015',
        roomId: 'room-mb',
        roomName: 'Master Bedroom',
        type: ElectricalPointType.switchPoint,
        label: '2-Gang 2-Way Bedside Headboard Switch',
        quantity: 1,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-02',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.35,
        yRatio: 0.65,
      ),

      // Bedroom 1
      ElectricalPoint(
        id: 'pt-016',
        roomId: 'room-b1',
        roomName: 'Bedroom 1',
        type: ElectricalPointType.light,
        label: 'Ceiling Light Fitting',
        quantity: 1,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-02',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.72,
        yRatio: 0.68,
      ),
      ElectricalPoint(
        id: 'pt-017',
        roomId: 'room-b1',
        roomName: 'Bedroom 1',
        type: ElectricalPointType.socketDouble,
        label: 'Study Desk & Bedside Double Sockets',
        quantity: 3,
        cableSize: '2.5 mm²',
        circuitId: 'SOCKET-03',
        protectionMcb: '20A MCB',
        status: 'Recommended',
        xRatio: 0.85,
        yRatio: 0.75,
      ),

      // Bathroom & Water Heater
      ElectricalPoint(
        id: 'pt-018',
        roomId: 'room-bth',
        roomName: 'Bathroom',
        type: ElectricalPointType.waterHeater,
        label: 'Instant Water Heater Supply Isolator',
        quantity: 1,
        cableSize: '4.0 mm²',
        circuitId: 'WATER-HEATER',
        protectionMcb: '20A MCB / 30mA RCD',
        status: 'Recommended',
        xRatio: 0.48,
        yRatio: 0.80,
      ),
      ElectricalPoint(
        id: 'pt-019',
        roomId: 'room-bth',
        roomName: 'Bathroom',
        type: ElectricalPointType.light,
        label: 'IP44 Moisture Resistant Light',
        quantity: 1,
        cableSize: '1.5 mm²',
        circuitId: 'LGT-02',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        xRatio: 0.52,
        yRatio: 0.75,
      ),
    ];
  }

  static List<Circuit> getCircuits() {
    return const [
      Circuit(
        id: 'c-01',
        code: 'LGT-01',
        name: 'Ground Floor Lighting',
        description: 'Living room, kitchen, front veranda, foyer points',
        pointsCount: 8,
        cableSize: '1.5 mm²',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        loadKw: 0.95,
      ),
      Circuit(
        id: 'c-02',
        code: 'LGT-02',
        name: 'Bedrooms & Bathrooms Lighting',
        description: 'Master bedroom, guest bedrooms, ensuite, and external porch',
        pointsCount: 6,
        cableSize: '1.5 mm²',
        protectionMcb: '10A MCB',
        status: 'Recommended',
        loadKw: 0.65,
      ),
      Circuit(
        id: 'c-03',
        code: 'SOCKET-01',
        name: 'Living Area Radial Sockets',
        description: 'Ring / radial socket circuit for lounge entertainment & media',
        pointsCount: 12,
        cableSize: '2.5 mm²',
        protectionMcb: '20A MCB',
        status: 'Recommended',
        loadKw: 2.80,
      ),
      Circuit(
        id: 'c-04',
        code: 'KITCHEN-01',
        name: 'Kitchen Heavy Appliances',
        description: 'Dedicated cooker unit, refrigerator, microwave countertop line',
        pointsCount: 4,
        cableSize: '4.0 mm²',
        protectionMcb: '25A MCB',
        status: 'Review',
        loadKw: 4.20,
      ),
      Circuit(
        id: 'c-05',
        code: 'WATER-HEATER',
        name: 'Dedicated Water Heating',
        description: 'Direct dedicated feed with 20A double pole neon isolator',
        pointsCount: 1,
        cableSize: '4.0 mm²',
        protectionMcb: '20A MCB',
        status: 'Recommended',
        loadKw: 3.00,
      ),
      Circuit(
        id: 'c-06',
        code: 'SPARE-01',
        name: 'Spare Way (Future Expansion)',
        description: 'Unallocated way in consumer unit for AC or Solar inverter',
        pointsCount: 0,
        cableSize: 'Unwired',
        protectionMcb: '16A MCB',
        status: 'Spare',
        loadKw: 0.00,
      ),
    ];
  }

  static List<BoqItem> getBoqItems() {
    return [
      // Cables
      const BoqItem(
        id: 'boq-01',
        category: BoqCategory.cables,
        item: '1.5 mm² Single Core Cable',
        specification: 'Copper conductor, PVC insulated 450/750V (Lighting circuits)',
        quantity: 180,
        unit: 'm',
        unitPriceRwf: 750,
      ),
      const BoqItem(
        id: 'boq-02',
        category: BoqCategory.cables,
        item: '2.5 mm² Single Core Cable',
        specification: 'Copper conductor, PVC insulated 450/750V (Power sockets)',
        quantity: 320,
        unit: 'm',
        unitPriceRwf: 1150,
      ),
      const BoqItem(
        id: 'boq-03',
        category: BoqCategory.cables,
        item: '4.0 mm² Heavy-Duty Cable',
        specification: 'Cooker & Water heater dedicated circuits',
        quantity: 60,
        unit: 'm',
        unitPriceRwf: 1800,
      ),
      const BoqItem(
        id: 'boq-04',
        category: BoqCategory.cables,
        item: '16.0 mm² Sub-Main Cable',
        specification: 'Double insulated PVC/PVC main intake cable',
        quantity: 25,
        unit: 'm',
        unitPriceRwf: 4200,
      ),

      // Lighting
      const BoqItem(
        id: 'boq-05',
        category: BoqCategory.lighting,
        item: 'LED Ceiling Downlight 18W',
        specification: 'Recessed warm white 3000K, aluminum heat sink, IP20',
        quantity: 14,
        unit: 'pcs',
        unitPriceRwf: 6500,
      ),
      const BoqItem(
        id: 'boq-06',
        category: BoqCategory.lighting,
        item: 'Waterproof Ceiling Fitting 12W',
        specification: 'IP44 rated moisture-resistant for bathrooms & veranda',
        quantity: 3,
        unit: 'pcs',
        unitPriceRwf: 7800,
      ),

      // Switches
      const BoqItem(
        id: 'boq-07',
        category: BoqCategory.switches,
        item: '1-Gang 2-Way Flush Switch',
        specification: '10AX 250V plate switch, white polycarbonate',
        quantity: 6,
        unit: 'pcs',
        unitPriceRwf: 3200,
      ),
      const BoqItem(
        id: 'boq-08',
        category: BoqCategory.switches,
        item: '2-Gang 1-Way Flush Switch',
        specification: '10AX 250V double rocker switch, white',
        quantity: 4,
        unit: 'pcs',
        unitPriceRwf: 4000,
      ),

      // Sockets
      const BoqItem(
        id: 'boq-09',
        category: BoqCategory.sockets,
        item: '13A Double Switched Socket',
        specification: 'BS 1363 twin switched socket outlet with shuttered pinholes',
        quantity: 18,
        unit: 'pcs',
        unitPriceRwf: 5500,
      ),
      const BoqItem(
        id: 'boq-10',
        category: BoqCategory.sockets,
        item: '45A Cooker Control Unit',
        specification: 'Double pole switch with neon indicator and 13A socket outlet',
        quantity: 1,
        unit: 'pcs',
        unitPriceRwf: 14500,
      ),

      // Protection & Distribution Board
      const BoqItem(
        id: 'boq-11',
        category: BoqCategory.distributionBoard,
        item: '8-Way Distribution Board',
        specification: 'Metalclad consumer unit enclosure with busbar & neutral link',
        quantity: 1,
        unit: 'set',
        unitPriceRwf: 45000,
      ),
      const BoqItem(
        id: 'boq-12',
        category: BoqCategory.protection,
        item: '63A 30mA 2-Pole RCD',
        specification: 'Residual Current Device for overall earth leakage protection',
        quantity: 1,
        unit: 'pcs',
        unitPriceRwf: 28000,
      ),
      const BoqItem(
        id: 'boq-13',
        category: BoqCategory.protection,
        item: '20A MCB Type B',
        specification: 'Miniature Circuit Breaker single pole 6kA breaking capacity',
        quantity: 5,
        unit: 'pcs',
        unitPriceRwf: 4500,
      ),
      const BoqItem(
        id: 'boq-14',
        category: BoqCategory.protection,
        item: '10A MCB Type B',
        specification: 'Miniature Circuit Breaker single pole 6kA breaking capacity',
        quantity: 3,
        unit: 'pcs',
        unitPriceRwf: 4200,
      ),
      const BoqItem(
        id: 'boq-15',
        category: BoqCategory.protection,
        item: '25A MCB Type B',
        specification: 'Miniature Circuit Breaker single pole 6kA for kitchen',
        quantity: 1,
        unit: 'pcs',
        unitPriceRwf: 4800,
      ),

      // Conduits & Accessories
      const BoqItem(
        id: 'boq-16',
        category: BoqCategory.conduits,
        item: '20mm Heavy Duty PVC Conduit',
        specification: '3-meter lengths rigid PVC conduit for concealed casting',
        quantity: 45,
        unit: 'pcs',
        unitPriceRwf: 2200,
      ),
      const BoqItem(
        id: 'boq-17',
        category: BoqCategory.accessories,
        item: 'Circular PVC Junction Boxes',
        specification: '20mm 2-way and 4-way through boxes with covers',
        quantity: 30,
        unit: 'pcs',
        unitPriceRwf: 800,
      ),
      const BoqItem(
        id: 'boq-18',
        category: BoqCategory.accessories,
        item: 'Copper Clad Earthing Rod Set',
        specification: '1.5m 5/8 inch copper bonded earth electrode with brass clamp',
        quantity: 1,
        unit: 'set',
        unitPriceRwf: 25000,
      ),
    ];
  }

  static const List<String> sampleFloorPlans = [
    'Kicukiro_Villa_Architectural_Plan.png',
    'Gacuriro_Residence_Plan_Final.pdf',
    'Kigali_Heights_Commercial_L1.png',
    'Nyarugenge_Duplex_Layout.jpg',
  ];
}
